---
    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: music-deployment
      labels:
        app: music
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: music
        spec:
          containers:
          - name: music
            image: fabiojapa/saka_python_django_rest_mongodb
            imagePullPolicy: Always 
            ports:
              - containerPort: 8000
            env:
              - name: MONGODB_URI
                value: "mongodb+srv://appuser:sAbweK71bPwiaZww@googlesp-4dth2.gcp.mongodb.net/test?retryWrites=true&w=majority"
              - name: MONGODB_USER
                value: "appuser"
              - name: MONGODB_PASSWORD
                value: "sAbweK71bPwiaZww"
                